# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: r
# https://blog.rstudio.org/2016/03/09/r-on-travis-ci/
sudo: false
cache: packages

env:
  - WARNINGS_ARE_ERRORS=1

r_github_packages:
  - jimhester/lintr # R lint testing
  - jimhester/covr  # code coverage check

after_success:
  - Rscript -e 'covr::codecov()'

branches:
  only:
    - master
    - dev
    - travis

notifications:
  email:
    on_success: change
    on_failure: change
